### ISSUE TITLE
This is trash

### ISSUE THREAD

**Issue by hoodr** [JoyceStick-BC/Snatch#13]
**Write better code**

**Comment by emaadali** [comment]
https://github.com/hoodr/hoodr.github.io

**Comment by hoodr** [comment]
Could be worse. Could be @reedery

**Comment by emaadali** [comment]
Nah man his repos are lit: https://github.com/reedery/fifteen

**Comment by hoodr** [comment]
Oh yeah, you're right. He's killing it. What about @evanotero. I bet he has some shit repos, or better yet @hartym12

**Comment by evanotero** [comment]
go away

**Comment by emaadali** [comment]
its a work in progress - he is still getting started: https://github.com/hartym12/SplitrRevamped
